name: CI Demo

on: [push]

jobs: 
  compile:
    runs-on: ubuntu-latest
    steps:
      name: Checkout to repo
      run: cd backend

      name: Install dependencies
      run: npm i

      name: Build the backend
      run: npm run build